# Milestone 1

## QA Pipeline

In [605]:
import nltk
import re
import pandas as pd
import glob
from nltk.corpus import stopwords
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\raedj\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\raedj\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\raedj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

### Load Dataset

In [606]:
import os

path = "data/QA"
files = os.listdir(path)

for f in files:
    with open(os.path.join(path, f), encoding="utf-8") as file:
        text = file.read()
        print(f, len(text))

0urc3PabvOs_QA.csv 39181
3AwL93uolIA_QA.csv 34114
8rcY34IA-6I_QA.csv 34706
8ZL2AAxQmLQ_QA.csv 42284
ArytJ_HZ-1E_QA.csv 42329
DbuoaakWh7g_QA.csv 35242
gv5hDK2YQfA_QA.csv 33161
IxsJEffQAZA_QA.csv 35730
MOEwXtL2DQ4_QA.csv 37415
nc8oJTETqoI_QA.csv 37153
NJ-JcDcff8o_QA.csv 38688
yc7x5jNhXIQ_QA.csv 34614
z2NGnjXG5uQ_QA.csv 40717

### All QA loadded into single DataFrame

In [607]:
files = glob.glob("data/QA/*.csv")

dfs = []
for f in files:
    temp = pd.read_csv(f)
    # temp["source_file"] = f
    dfs.append(temp)

df_train = pd.concat(dfs, ignore_index=True)

### Inspect the Dataset

In [608]:
df_train.head()

,video_id,video_title,question_id,question,answer,difficulty
0,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q001,ماذا ورد في هذا الموضع من النص؟,"افتح موضوع جديد يا ""ميدو""، أنا مش ناقص!",Easy
1,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q002,ما الجملة المذكورة في هذا السياق؟,وبعد كدا، هتنطفي هي كمان.,Medium
2,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q003,كيف صيغت العبارة هنا؟,- أيوة.,Easy
3,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q004,ما الذي قيل في هذا الجزء؟,- عشان كُل حاجة بتنتهي.,Medium
4,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q005,ما النص الحرفي المذكور في هذه الفقرة؟,- عشان الفيزيا بتقول كدا.,Easy

In [609]:
df_train["question_length"] = df_train["question"].apply(len)
df_train["answer_length"] = df_train["answer"].apply(len)

print(df_train.describe())

       question_length  answer_length
count      3890.000000    3890.000000
mean         29.481234      27.937532
std           5.950017       8.209206
min          14.000000       3.000000
25%          25.000000      21.000000
50%          31.000000      28.000000
75%          33.000000      34.000000
max          38.000000      52.000000

In [610]:
from collections import Counter

path = "data/QA"
files = os.listdir(path)

for f in files:
    with open(os.path.join(path, f), encoding="utf-8") as file:
        text = file.read()
        words = text.split()
        freq = Counter(words)
        
for word, count in freq.most_common(50):
    print(f"{word}: {count}")

إلى: 301
z2NGnjXG5uQ,كيف: 300
تحولت: 300
روسيا: 300
إمبراطورية؟: 300
|: 300
في: 265
هذا: 184
من: 84
هذه: 64
ورد: 60
الموضع: 60
الجملة: 60
المذكورة: 60
صيغت: 60
العبارة: 60
الذي: 60
قيل: 60
النص: 60
الحرفي: 60
المذكور: 60
على: 24
اللي: 21
ما: 10
""بطرس"": 10
عن: 8
كل: 7
هو: 7
القيصر: 6
عشان: 6
دي: 5
""روسيا""،",Easy: 5
قيصر: 5
زي: 5
كان: 5
مش: 5
إن: 5
مع: 4
""روسيا"": 4
الزوجة: 4
هُما: 4
هنا؟,اللي: 4
حكيتلك: 4
العالم: 4
فيه: 4
""البحر: 4
الجزء؟,من: 3
ياخد: 3
بحر: 3
كدا: 3

In [611]:
all_words = " ".join(df_train["answer"].astype(str)).split()

freq = Counter(all_words)

for word, count in freq.most_common(50):
    print(f"{word}: {count}")

في: 718
اللي: 410
من: 393
ما: 261
على: 244
إن: 208
يا: 152
كان: 134
هو: 98
مش: 94
زي: 91
كل: 89
عشان: 88
فيها: 82
غير: 75
دا: 70
كانت: 67
عزيزي،: 67
هي: 66
احنا: 63
جدًا: 62
عن: 60
انت: 60
ولاية: 60
"تكساس".: 60
الطيارة: 60
دي: 57
مع: 56
اسمها: 49
هذا: 48
وهو: 48
أو: 47
أنا: 46
بشكل: 45
كدا،: 44
هذه: 42
العالم: 42
حاجة: 41
-: 40
ممكن: 40
إنه: 40
أي: 38
إلى: 37
دلوقتي،: 37
الأمريكي: 37
بس: 36
فيه: 33
ولا: 33
واقف: 32
أقدم: 32

In [612]:
from pathlib import Path
from difflib import get_close_matches

TRANSCRIPTS_DIR = Path("data/Transcripts")

def normalize_arabic_text(text: str) -> str:
    text = str(text).strip().lower()
    # remove zero width characters
    text = re.sub(r'[\u200B-\u200D\uFEFF]', '', text)
    # remove Arabic diacritics
    text = re.sub(r'[\u0617-\u061A\u064B-\u0652]', '', text)
    # normalize common Arabic letter variants
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ة", "ه", text)
    text = re.sub(r"گ", "ك", text)
    text = text.replace("ـ", "")
    return text

def remove_timestamps(text):
    return re.sub(r'\d+\.\d+:', '', text)

def normalize_title(title: str) -> str:
    t = normalize_arabic_text(title)
    t = t.replace(".txt", "")
    t = re.sub(r"\bالدحيح\b", "", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t

def tokenize_words(text: str):
    # keep Arabic/English word tokens only
    return re.findall(r"[\w]+", str(text), flags=re.UNICODE)

def normalize_tokens(tokens):
    normalized = []
    for tok in tokens:
        nt = normalize_arabic_text(tok)
        nt = re.sub(r"[^\w]", "", nt, flags=re.UNICODE)
        if nt:
            normalized.append(nt)
    return normalized

def find_sublist_index(haystack, needle):
    if not needle or len(needle) > len(haystack):
        return -1
    n = len(needle)
    for i in range(len(haystack) - n + 1):
        if haystack[i:i+n] == needle:
            return i
    return -1

# Build transcript index keyed by normalized title
transcript_index = {}
for transcript_path in TRANSCRIPTS_DIR.glob("*.txt"):
    raw_text = transcript_path.read_text(encoding="utf-8")
    raw_text = remove_timestamps(raw_text)
    original_tokens = tokenize_words(raw_text)
    normalized_tokens = normalize_tokens(original_tokens)

    key = normalize_title(transcript_path.stem)
    transcript_index[key] = {
        "path": transcript_path,
        "original_tokens": original_tokens,
        "normalized_tokens": normalized_tokens
    }

def match_transcript_key(video_title: str):
    key = normalize_title(video_title)
    if key in transcript_index:
        return key
    # fallback fuzzy match if title is slightly different
    matches = get_close_matches(key, list(transcript_index.keys()), n=1, cutoff=0.55)
    return matches[0] if matches else None

def extract_context_from_row(row, window=20):
    matched_key = match_transcript_key(row["video_title"])
    if not matched_key:
        return ""

    answer_tokens = tokenize_words(str(row["answer"]))
    answer_tokens_norm = normalize_tokens(answer_tokens)
    if not answer_tokens_norm:
        return ""

    transcript = transcript_index[matched_key]
    idx = find_sublist_index(transcript["normalized_tokens"], answer_tokens_norm)
    if idx == -1:
        return ""

    start = max(0, idx - window)
    end = min(len(transcript["original_tokens"]), idx + len(answer_tokens_norm) + window)
    # keep context in original (non-normalized) transcript form
    return " ".join(transcript["original_tokens"][start:end])

# Add context column
df_train["context"] = df_train.apply(extract_context_from_row, axis=1)

# Optional quick quality check
found_ratio = (df_train["context"].str.len() > 0).mean() * 100
print(f"Context extracted for {found_ratio:.1f}% of rows")
df_train[["video_title", "answer", "context"]].head()

Context extracted for 100.0% of rows

,video_title,answer,context
0,مصير الأرض و الشمس و كل شيء | الدحيح,"افتح موضوع جديد يا ""ميدو""، أنا مش ناقص!",بابا بابا بابا هو احنا جينا ازاي لأ دا السؤال ...
1,مصير الأرض و الشمس و كل شيء | الدحيح,وبعد كدا، هتنطفي هي كمان.,بتاع امبارح افتح موضوع جديد يا ميدو أنا مش ناق...
2,مصير الأرض و الشمس و كل شيء | الدحيح,- أيوة.,مش ناقص طيب الشمس هتفضل منو رة لحد امتى لحد نه...
3,مصير الأرض و الشمس و كل شيء | الدحيح,- عشان كُل حاجة بتنتهي.,طيب الشمس هتفضل منو رة لحد امتى لحد نهاية الكو...
4,مصير الأرض و الشمس و كل شيء | الدحيح,- عشان الفيزيا بتقول كدا.,امتى لحد نهاية الكون وبعد كدا هتنطفي هي كمان ه...

### Clean And normalize Text Fields

In [613]:
def process_text_column(df, column_name):

    df[column_name] =df[column_name].apply(remove_stopwords_and_punctuation_from_text)
    df[column_name] =df[column_name].apply(normalize_text)
    return df

def remove_stopwords_and_punctuation_from_text(text):
    nltk_stop_words = set(stopwords.words('arabic'))


    # punctuation ='!"$%&()*,-./:;<=>?@[\\]^_`{|}~'
    punctuation = [
    "،","؛","؟","ـ","«","»","‹","›","“","”","‘","’",
    ".",",",";",":","!","?","-","_","(",")","[","]","{","}",
    "\"","'","/","\\","|","@","#","$","%","^","&","*","+","=","<",">","~","`","``","''"
    ]
    for p in punctuation:
        text = text.replace(p, '')

    tokens = nltk.word_tokenize(text)

    filtered_tokens = [word for word in tokens if word not in nltk_stop_words]
    # Join the tokens back into a string
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text



def normalize_text(text):
    
    # 1. Convert English letters to lowercase
    text = text.lower()
    
    # 2. Remove Arabic Tashkeel (diacritics)
    tashkeel = r'[\u0617-\u061A\u064B-\u0652]'
    text = re.sub(tashkeel, '', text)

    # 3. Normalize Arabic letters
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    # text = re.sub("ؤ", "و", text)
    # text = re.sub("ئ", "ي", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("گ", "ك", text)

    # 4. Remove Tatweel (ـ)
    text = re.sub("ـ", "", text)

    return text

In [614]:
process_text_column(df_train, "question")

,video_id,video_title,question_id,question,answer,difficulty,question_length,answer_length,context
0,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q001,الموضع النص,"افتح موضوع جديد يا ""ميدو""، أنا مش ناقص!",Easy,31,39,بابا بابا بابا هو احنا جينا ازاي لأ دا السؤال ...
1,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q002,الجمله المذكوره السياق,وبعد كدا، هتنطفي هي كمان.,Medium,33,25,بتاع امبارح افتح موضوع جديد يا ميدو أنا مش ناق...
2,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q003,صيغت العباره,- أيوة.,Easy,21,7,مش ناقص طيب الشمس هتفضل منو رة لحد امتى لحد نه...
3,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q004,قيل الجزء,- عشان كُل حاجة بتنتهي.,Medium,25,23,طيب الشمس هتفضل منو رة لحد امتى لحد نهاية الكو...
4,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q005,النص الحرفي المذكور الفقره,- عشان الفيزيا بتقول كدا.,Easy,37,25,امتى لحد نهاية الكون وبعد كدا هتنطفي هي كمان ه...
...,...,...,...,...,...,...,...,...,...
3885,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q296,الموضع النص,"""تشارلز"" افتكر إن ""بطرس"" هرب من المعركة،",Medium,31,40,المعركة بالشكل المهين والم ذ ل دا خل ت تشارلز ...
3886,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q297,الجمله المذكوره السياق,"ويخش ياخد ""روسيا""،",Easy,33,18,ودا خل اه ما يعتمدش الروس تاني وما يشوفهومش قو...
3887,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q298,صيغت العباره,"أخطر عنصر في ""الاتحاد""،",Medium,21,23,ما يكم ل على موسكو ويخش ياخد روسيا هيقرر إن هو...
3888,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q299,قيل الجزء,"""بولندا""، الخصم الصعب العنيف،",Easy,25,29,كان شايفها أخطر عنصر في الاتحاد ودي يا عزيزي ك...
3889,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q300,النص الحرفي المذكور الفقره,وتعافى من صدمة الخسارة المذلة،,Medium,37,30,عزيزي هيخش بولندا الخصم الصعب العنيف ويفضل سني...

In [615]:
process_text_column(df_train, "answer")

,video_id,video_title,question_id,question,answer,difficulty,question_length,answer_length,context
0,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q001,الموضع النص,افتح موضوع جديد ميدو مش ناقص,Easy,31,39,بابا بابا بابا هو احنا جينا ازاي لأ دا السؤال ...
1,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q002,الجمله المذكوره السياق,وبعد كدا هتنطفي كمان,Medium,33,25,بتاع امبارح افتح موضوع جديد يا ميدو أنا مش ناق...
2,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q003,صيغت العباره,ايوه,Easy,21,7,مش ناقص طيب الشمس هتفضل منو رة لحد امتى لحد نه...
3,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q004,قيل الجزء,عشان كل حاجه بتنتهي,Medium,25,23,طيب الشمس هتفضل منو رة لحد امتى لحد نهاية الكو...
4,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q005,النص الحرفي المذكور الفقره,عشان الفيزيا بتقول كدا,Easy,37,25,امتى لحد نهاية الكون وبعد كدا هتنطفي هي كمان ه...
...,...,...,...,...,...,...,...,...,...
3885,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q296,الموضع النص,تشارلز افتكر بطرس هرب المعركه,Medium,31,40,المعركة بالشكل المهين والم ذ ل دا خل ت تشارلز ...
3886,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q297,الجمله المذكوره السياق,ويخش ياخد روسيا,Easy,33,18,ودا خل اه ما يعتمدش الروس تاني وما يشوفهومش قو...
3887,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q298,صيغت العباره,اخطر عنصر الاتحاد,Medium,21,23,ما يكم ل على موسكو ويخش ياخد روسيا هيقرر إن هو...
3888,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q299,قيل الجزء,بولندا الخصم الصعب العنيف,Easy,25,29,كان شايفها أخطر عنصر في الاتحاد ودي يا عزيزي ك...
3889,z2NGnjXG5uQ,كيف تحولت روسيا إلى إمبراطورية؟ | الدحيح,z2NGnjXG5uQ_Q300,النص الحرفي المذكور الفقره,وتعافي صدمه الخساره المذله,Medium,37,30,عزيزي هيخش بولندا الخصم الصعب العنيف ويفضل سني...

In [616]:
df_train["answer_length"] = df_train["answer"].apply(len)
df_train.head()

,video_id,video_title,question_id,question,answer,difficulty,question_length,answer_length,context
0,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q001,الموضع النص,افتح موضوع جديد ميدو مش ناقص,Easy,31,28,بابا بابا بابا هو احنا جينا ازاي لأ دا السؤال ...
1,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q002,الجمله المذكوره السياق,وبعد كدا هتنطفي كمان,Medium,33,20,بتاع امبارح افتح موضوع جديد يا ميدو أنا مش ناق...
2,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q003,صيغت العباره,ايوه,Easy,21,4,مش ناقص طيب الشمس هتفضل منو رة لحد امتى لحد نه...
3,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q004,قيل الجزء,عشان كل حاجه بتنتهي,Medium,25,19,طيب الشمس هتفضل منو رة لحد امتى لحد نهاية الكو...
4,0urc3PabvOs,مصير الأرض و الشمس و كل شيء | الدحيح,0urc3PabvOs_Q005,النص الحرفي المذكور الفقره,عشان الفيزيا بتقول كدا,Easy,37,22,امتى لحد نهاية الكون وبعد كدا هتنطفي هي كمان ه...

In [617]:
df_train[df_train["answer_length"] == 5]

,video_id,video_title,question_id,question,answer,difficulty,question_length,answer_length,context
496,3AwL93uolIA,الساموراي | الدحيح,3AwL93uolIA_Q197,الجمله المذكوره الموضع,اتنين,Easy,33,5,اللي اتعفى عنه ولم ا مات بعد سنين اتدفن يا عزي...
640,8rcY34IA-6I,الأخطبوط | الدحيح,8rcY34IA-6I_Q041,النص الفقره رقم 41,نخدره,Easy,37,5,عزيزي كنا بنتعامل مع الأخطبوط دا على إنه لافقا...
649,8rcY34IA-6I,الأخطبوط | الدحيح,8rcY34IA-6I_Q050,النص الفقره رقم 50,عزيزي,Medium,37,5,هو ب قه فين خل يني يا عزيزي أقول ك إن ب ق الأخ...
711,8rcY34IA-6I,الأخطبوط | الدحيح,8rcY34IA-6I_Q112,النص الفقره رقم 112,يقولك,Medium,38,5,ا كنت سام فالأخطبوط ممكن يلعب برضه بالحيلة دي ...
897,8ZL2AAxQmLQ,كيف تنقل جبل وزنه 30 طن قبل أن يغرق؟ | الدحيح,8ZL2AAxQmLQ_Q008,صيغت العباره,حرامي,Medium,21,5,بدري انت كل يوم تمشي بدري من الشغل يعني مش لطي...
1228,ArytJ_HZ-1E,هل Citizen Kane أفضل فيلم في التاريخ؟ | الدحيح,ArytJ_HZ-1E_Q039,قيل الجزء,زاندو,Easy,25,5,لساني ما سهلة أهي سهلة اسمع رك ز معايا أنا ساي...
1229,ArytJ_HZ-1E,هل Citizen Kane أفضل فيلم في التاريخ؟ | الدحيح,ArytJ_HZ-1E_Q040,النص الحرفي المذكور الفقره,زبادو,Medium,37,5,ما سهلة أهي سهلة اسمع رك ز معايا أنا سايبلكم ع...
1337,ArytJ_HZ-1E,هل Citizen Kane أفضل فيلم في التاريخ؟ | الدحيح,ArytJ_HZ-1E_Q148,صيغت العباره,الوقت,Medium,21,5,السينما مكان بنلجأله عشان نهرب من واقعنا الحزي...
2679,MOEwXtL2DQ4,فيزياء و فلسفة الحركة | الدحيح,MOEwXtL2DQ4_Q290,النص الحرفي المذكور الفقره,الوقت,Medium,37,5,أد إيه هيقول ولا حاجة صفر طب والمسافة يا ضوء ص...
2711,nc8oJTETqoI,منابع النيل | الدحيح,nc8oJTETqoI_Q022,الجمله المذكوره السياق,طبقيص,Medium,33,5,في الفريزر كتير بحيث كده بقى انا عايز كوبايه ا...
3144,NJ-JcDcff8o,كيف تسيطر على عقول البشر؟ | الدحيح,NJ-JcDcff8o_Q155,النص الحرفي المذكور الفقره,بتخرج,Easy,37,5,اللي عم نا جونز عم ال يخططلها إلا إنهم بيتفاجئ...
3203,NJ-JcDcff8o,كيف تسيطر على عقول البشر؟ | الدحيح,NJ-JcDcff8o_Q214,قيل الجزء,كلمتي,Medium,25,5,الوحشة النهاردة ولازم تتضرب باللوح هتيجي بقى ت...
3337,yc7x5jNhXIQ,جون كينيدي | الدحيح,yc7x5jNhXIQ_Q048,صيغت العباره,يظهرش,Medium,21,5,عزيزي كان مثالي لأنه لم يك ن مسموح لأي شيء غير...

In [618]:
all_words = " ".join(df_train["answer"].astype(str)).split()

freq = Counter(all_words)

for word, count in freq.most_common(50):
    print(f"{word}: {count}")

اللي: 411
دا: 116
عزيزي: 99
مش: 96
دي: 93
جدا: 92
زي: 92
عشان: 89
كدا: 75
احنا: 67
كانت: 67
انت: 63
حاجه: 62
تكساس: 61
ولايه: 60
الطياره: 60
العالم: 57
اسمها: 49
بشكل: 45
دلوقتي: 45
سنه: 44
الامريكي: 42
ممكن: 41
الله: 38
عادي: 34
مارتن: 34
ضوئيه: 33
النيل: 33
لانه: 33
الناس: 32
واقف: 32
اقدم: 32
صعب: 32
7: 32
لحد: 31
المعبد: 31
هتغير: 31
2011: 30
لحضرتك: 30
فخر: 30
الطيران: 30
الf35: 30
لوكهيد: 30
هيجرب: 30
الرادار: 30
يلقطها: 30
لغات: 30
المقدم: 30
ايريك: 30
سميث: 30

In [619]:
# print("أنت" in stopwords.words('arabic'))

In [620]:
# Save the processed DataFrame to a new CSV file
# df_train.to_csv("output.csv", index=False, encoding="utf-8-sig")

## Transcripts Pipeline

### Load Dataset

In [621]:
import os

path = "data/Transcripts"
files = os.listdir(path)

for f in files:
    with open(os.path.join(path, f), encoding="utf-8") as file:
        text = file.read()
        print(f, len(text))

أعظم طائرة حربية  الدحيح.txt 38222
الأخطبوط  الدحيح.txt 38054
الساموراي  الدحيح.txt 34077
تاج محل  الدحيح.txt 26431
جون كينيدي  الدحيح.txt 56962
فيزياء و فلسفة الحركة  الدحيح.txt 47095
كيف تحولت روسيا إلى إمبراطورية؟  الدحيح.txt 59094
كيف تسيطر على عقول البشر؟  الدحيح.txt 45570
كيف تنقل جبل وزنه 30 طن قبل أن يغرق؟  الدحيح.txt 38574
مصير الأرض و الشمس و كل شيء  الدحيح.txt 33909
معركة ذي قار  الدحيح.txt 51260
منابع النيل  الدحيح.txt 49836
هل Citizen Kane أفضل فيلم في التاريخ؟  الدحيح.txt 35210

In [622]:
all_transcripts = ""

files = glob.glob("data/Transcripts/*.txt")

for file_path in files:
    with open(file_path, encoding="utf-8") as file:
        text = file.read()

    all_transcripts += text

print(all_transcripts[:500])  # preview first 500 characters

0.0: سيادة الكولونيل، صبرك في محله،
3.076: مبروك علينا،
4.238: عملنا أفجر طيارة في تاريخ "أمريكا".
6.184: أنا متحمس جدًا من امبارح،
8.308: ها، ورّيني!
9.435: أقدم لحضرتك فخر الطيران الأمريكي
12.205: الـF-35.
15.218: بس دي شكلها شبه اللي احنا عملناها قبل كدا!
17.977: آه، بس التكنولوجيا اللي فيها
سابقة بسنين ضوئية، حضرتك.
22.165: يعني إيه سنين ضوئية؟!
23.379: مش مهم، مش مهم، احكيلي عنها كدا.
25.494: القطعة الفنية اللي أمام حضرتك دي
فيها أقوى كمبيوتر،
29.108: كمبيونر نسـ....
30.058: معلش، يعني، سؤا

### Inspect the Dataset

In [623]:
from collections import Counter

path = "data/Transcripts"
files = os.listdir(path)

for f in files:
    with open(os.path.join(path, f), encoding="utf-8") as file:
        text = file.read()
        words = text.split()
        freq = Counter(words)
        
        print(freq.most_common(20))

[('يا', 142), ('في', 128), ('عزيزي،', 120), ('اللي', 102), ('على', 90), ('من', 88), ('ما', 83), ('إن', 67), ('دا', 45), ('مش', 41), ('دي', 36), ('هو', 36), ('انت', 33), ('طيارة', 32), ('الطيارة', 30), ('عشان', 29), ('كل', 29), ('كان', 28), ('احنا', 23), ('الـF-35', 21)]
[('يا', 134), ('في', 122), ('عزيزي،', 94), ('ما', 85), ('إن', 82), ('من', 82), ('على', 68), ('الأخطبوط', 65), ('اللي', 64), ('هو', 44), ('دا', 42), ('زي', 39), ('مش', 38), ('كدا،', 34), ('انت', 31), ('كل', 31), ('عشان', 31), ('بس', 28), ('لمّا', 26), ('فيه', 25)]
[('يا', 124), ('في', 113), ('عزيزي،', 110), ('كان', 65), ('من', 63), ('اللي', 63), ('الساموراي', 57), ('إن', 56), ('ما', 49), ('على', 33), ('كانوا', 31), ('دا', 30), ('أو', 29), ('كانت', 29), ('عشان', 28), ('زي', 25), ('مش', 24), ('هُما', 21), ('كدا،', 21), ('هو', 19)]
[('في', 96), ('يا', 91), ('عزيزي،', 67), ('من', 66), ('اللي', 64), ('ما', 50), ('على', 47), ('إن', 39), ('دا', 32), ('مش', 31), ('كان', 28), ('كل', 24), ('زي', 22), ('دي', 22), ('"تاج', 21), ('"شاه', 20), ('عشان', 20), ('محل"', 19), ('جهان"', 18), ('حاجة', 18)]
[('في', 241), ('من', 139), ('اللي', 138), ('إن', 116), ('ما', 110), ('يا', 102), ('كان', 100), ('على', 87), ('عزيزي،', 73), ('دا', 44), ('مش', 42), ('"كينيدي"', 41), ('هو', 40), ('كل', 39), ('كانت', 39), ('احنا', 38), ('عشان', 31), ('"أمريكا"', 30), ('"أوزوالد"', 29), ('"جون', 26)]
[('في', 196), ('يا', 193), ('عزيزي،', 150), ('من', 114), ('ما', 113), ('إن', 103), ('اللي', 89), ('على', 61), ('دا', 60), ('لو', 47), ('مش', 45), ('انت', 45), ('كل', 39), ('دي', 34), ('سرعة', 33), ('زي', 31), ('هو', 30), ('الضوء', 29), ('أنا', 28), ('عشان', 27)]
[('في', 175), ('اللي', 154), ('من', 150), ('يا', 144), ('ما', 131), ('على', 121), ('إن', 105), ('عزيزي،', 104), ('"بطرس"', 90), ('كان', 76), ('كل', 55), ('عشان', 48), ('هو', 41), ('مش', 38), ('"روسيا"', 38), ('دا', 36), ('أنا', 35), ('دي', 33), ('كانت', 30), ('ولكن', 29)]
[('في', 150), ('يا', 117), ('اللي', 109), ('ما', 100), ('من', 96), ('إن', 87), ('على', 80), ('عزيزي،', 76), ('كان', 68), ('دا', 50), ('"جونز"', 50), ('انت', 43), ('مش', 39), ('كل', 36), ('هو', 36), ('أنا', 30), ('دي', 30), ('مع', 28), ('زي', 23), ('بس', 23)]
[('يا', 207), ('عزيزي،', 171), ('في', 137), ('من', 99), ('اللي', 94), ('ما', 80), ('على', 67), ('إن', 53), ('المعبد', 33), ('كان', 32), ('دا،', 29), ('زي', 27), ('كل', 26), ('عشان', 25), ('كانت', 24), ('مش', 23), ('كدا،', 23), ('المعبد،', 23), ('"أبو', 23), ('معبد', 23)]
[('في', 151), ('يا', 107), ('اللي', 84), ('عزيزي،', 79), ('من', 66), ('إن', 66), ('الكون', 50), ('ما', 47), ('على', 42), ('دا', 32), ('كل', 32), ('دي', 30), ('مش', 26), ('فيه', 23), ('زي', 23), ('لو', 22), ('هو', 20), ('عشان', 20), ('هذه', 20), ('سنة', 20)]
[('يا', 238), ('عزيزي،', 197), ('في', 153), ('من', 119), ('ما', 107), ('اللي', 104), ('على', 90), ('إن', 89), ('كان', 60), ('هو', 52), ('دا', 51), ('كسرى', 48), ('بن', 47), ('مش', 42), ('أنا', 37), ('العرب', 32), ('الفُرس', 31), ('لو', 30), ('كسرى،', 30), ('بني', 29)]
[('في', 185), ('من', 139), ('اللي', 123), ('ما', 111), ('يا', 109), ('ان', 104), ('عزيزي', 95), ('بيرتون', 81), ('سبيك', 72), ('كان', 66), ('على', 62), ('هو', 49), ('ده', 49), ('النيل', 46), ('دي', 43), ('مش', 42), ('انه', 38), ('له', 37), ('كده', 36), ('البعثه', 33)]
[('في', 148), ('يا', 98), ('اللي', 88), ('عزيزي،', 72), ('من', 71), ('ما', 69), ('إن', 53), ('كان', 46), ('زي', 39), ('مش', 38), ('على', 37), ('كل', 36), ('عشان', 35), ('هو', 32), ('"ويلز"', 32), ('دا', 31), ('بس', 29), ('الفيلم', 23), ('عن', 23), ('فيلم', 22)]

### Clean And normalize Text Fields

In [624]:
def process_text_transcript(text):
    text = remove_timestamps(text)
    text = remove_stopwords_and_punctuation_from_text(text)
    text = normalize_text(text)
    return text

def remove_timestamps(text):
    return re.sub(r'\d+\.\d+:', '', text)

In [625]:
processed_text = process_text_transcript(all_transcripts)
# df_train["context"] = processed_text

In [626]:
# Save processed text
# output_path = "processed_transcript.txt"
# with open(output_path, "w", encoding="utf-8") as file:
#     file.write(processed_text)

## Tokenizer

In [627]:
tokenizer = Tokenizer(
    num_words=20000,
    split=' ',
    char_level=False,
    oov_token="<OOV>"
  )

In [628]:
# fit on data
all_texts = list(df_train['question']) + [processed_text]
tokenizer.fit_on_texts(all_texts)

In [629]:
# use this to get insight on the Tokenizer
vocab_list = tokenizer.word_index

In [630]:
from sklearn.model_selection import train_test_split

df["input_text"] = df["question"] + " " + df["context"]

X_train, X_test, y_train, y_test = train_test_split(
    df["input_text"],
    df["answer"],
    test_size=0.2,
    random_state=42
)

train_sequences = tokenizer.texts_to_sequences(X_train)

KeyError: 'context'

### Padding

In [ ]:
# # Padding
trunc_type='post'
padding_type='post'
max_length=62000

train_padded = pad_sequences(
    train_sequences,
    maxlen=max_length,
    padding=padding_type,
    truncating=trunc_type
)

### Tokenizer Visualizations

In [ ]:
import matplotlib.pyplot as plt

# --- 2. Vocabulary stats ---
total_vocab = len(vocab_list)
capped_vocab = min(total_vocab, 20000)
print(f"Total unique tokens (full vocab):  {total_vocab}")
print(f"Vocab size used (num_words cap):   {capped_vocab}")

# Top 30 most frequent words (lowest index = highest frequency)
top_n = 30
top_words = sorted(vocab_list.items(), key=lambda x: x[1])[:top_n]
words_labels = [w for w, _ in top_words]
word_indices = [i for _, i in top_words]

fig, ax = plt.subplots(figsize=(14, 6))
ax.barh(words_labels, word_indices, color='steelblue')
ax.invert_yaxis()
ax.set_xlabel('Token Index (lower index = more frequent)')
ax.set_title(f'Top {top_n} Most Frequent Tokens in Vocabulary')
plt.tight_layout()
plt.show()

In [ ]:
import numpy as np

# --- 3. Sequence length distribution (before padding) ---
seq_lengths = [len(s) for s in train_sequences]

print(f"Sequence lengths — min: {min(seq_lengths)}, max: {max(seq_lengths)}, "
      f"mean: {np.mean(seq_lengths):.1f}, median: {np.median(seq_lengths):.1f}")
print(f"% sequences <= max_length ({max_length}): "
      f"{100 * np.mean(np.array(seq_lengths) <= max_length):.1f}%")

fig, ax = plt.subplots(figsize=(10, 4))
ax.hist(seq_lengths, bins=40, color='teal', edgecolor='white')
ax.axvline(max_length, color='red', linestyle='--', label=f'max_length = {max_length}')
ax.axvline(np.mean(seq_lengths), color='orange', linestyle='--',
           label=f'mean = {np.mean(seq_lengths):.1f}')
ax.set_xlabel('Sequence Length (tokens)')
ax.set_ylabel('Count')
ax.set_title('Distribution of Sequence Lengths Before Padding')
ax.legend()
plt.tight_layout()
plt.show()

In [ ]:
# --- 4. Padding zero-ratio + sample decode ---
zero_ratio = (train_padded == 0).sum() / train_padded.size
print(f"Padded matrix shape:  {train_padded.shape}")
print(f"Zero (pad) tokens:    {zero_ratio*100:.1f}% of all positions")

# Pie chart: padding vs real tokens  |  Line chart: token IDs of first sample
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].pie(
    [1 - zero_ratio, zero_ratio],
    labels=['Real tokens', 'Padding zeros'],
    autopct='%1.1f%%',
    colors=['steelblue', 'lightgray'],
    startangle=90
)
axes[0].set_title('Padding vs Real Tokens')

sample_seq = train_padded[0]
non_pad = sample_seq[sample_seq != 0]
axes[1].plot(range(len(non_pad)), non_pad, marker='o', markersize=3,
             linewidth=0.8, color='steelblue')
axes[1].set_xlabel('Token Position')
axes[1].set_ylabel('Token ID')
axes[1].set_title('Token IDs for Sample[0] (non-pad tokens)')

plt.tight_layout()
plt.show()

# Decode sample back to words
reverse_vocab = {v: k for k, v in vocab_list.items()}
decoded = [reverse_vocab.get(int(t), '<OOV>') for t in non_pad[:20]]
print("\nFirst 20 decoded tokens of sample[0]:")
print(' '.join(decoded))